### ISSUE TITLE
TA-PROGRES1 masalah dan berita pendukung 

### ISSUE THREAD

**Issue by BIMA-25** [BIMA-25/Final_Project_KEL8#1]
cari masalah dan berita pendukung yang berhubungan dengan project merancang sistem monitoring kualitas udara di ruangan tertutup berbasis iot

**Comment by afifahfau246** [comment]
Masalah: 
Kurangnya perhatian terhadap kualitas udara di ruangan tertutup dapat menyebabkan beberapa masalah yang dapat mempengaruhi kesehatan dan kenyamanan penghuni.
●	Polusi Udara Dalam Ruangan: Ruangan tertutup dapat menjadi tempat berkumpulnya berbagai polutan seperti partikel debu, serbuk sari, asap rokok, bahan kimia, gas beracun, dan zat-zat berbahaya lainnya. Pajanan jangka panjang terhadap polusi udara dalam ruangan dapat menyebabkan iritasi mata, hidung, dan tenggorokan, masalah pernapasan, alergi, dan bahkan penyakit serius seperti kanker paru-paru.
●	Gangguan Pernapasan: Kualitas udara yang buruk di ruangan tertutup dapat menyebabkan masalah pernapasan seperti sesak napas, batuk, dan mengi. Hal ini dapat berdampak negatif pada kesehatan paru-paru dan sistem pernapasan secara umum, terutama pada individu yang memiliki masalah pernapasan seperti asma atau penyakit paru obstruktif kronik (PPOK).
●	Masalah Kesehatan Kronis: Paparan jangka panjang terhadap polusi udara dalam ruangan dapat berkontribusi pada perkembangan masalah kesehatan kronis, termasuk penyakit kardiovaskular, penyakit pernapasan, dan penyakit perubahan neurologis. Orang yang menghabiskan waktu lebih lama di dalam ruangan tertutup yang terpolusi berisiko lebih tinggi mengalami masalah kesehatan jangka panjang.
Dalam ruangan tertutup, penting untuk memperhatikan dan menjaga kualitas udara agar tetap bersih, segar, dan sehat. Tindakan pencegahan seperti ventilasi yang baik, membersihkan secara rutin, mengontrol kelembaban, dan menghindari penggunaan bahan kimia berbahaya dapat membantu mengurangi masalah yang terkait dengan kualitas udara yang buruk di ruangan tertutup. 
Solusi: 
sehingga perlu adanya alat yang mampu membantu kita dalam pemantauan kualitas udara, maka dari itu kami disini ingin membuat alat yang mampu memantau kualitas udara di ruangan yang dapat kita ambil datanya secara realtime melalui platform iot sehingga pemantauan dapat dilakukan kapanpun dan dimanapun.

**Comment by BIMA-25** [comment]
sudah di review
