### ISSUE TITLE
TA-PROGRES 3 Project Timeline

### ISSUE THREAD

**Issue by BIMA-25** [BIMA-25/Final_Project_KEL8#12]
BIKIN PROJECT TIME LINE DENGAN DARI TANGGAL 19 MEI SAMPAI 20 JUNI

**Comment by afifahfau246** [comment]
![WhatsApp Image 2023-05-29 at 22 19 31](https://github.com/BIMA-25/Final_Project_KEL8/assets/130945743/4849accc-c0b4-46e2-9a00-59dacb0935f6)

**Comment by BIMA-25** [comment]
mantep
