### ISSUE TITLE
TA-PROGRES 3 Firmware (bikin flowchart alur pemrogramannya)

### ISSUE THREAD

**Issue by BIMA-25** [BIMA-25/Final_Project_KEL8#15]
BIKIN 
- flowchart koneksi ketelegram
- flowchart koneksi ke blynk
- flowchart alat

**Comment by BIMA-25** [comment]
agnan kamu bikin flowchart koneksi ketelegram ama flowchart koneksi ke blynk ya

aku flowchart alat

**Comment by BIMA-25** [comment]
![fikk](https://github.com/BIMA-25/Final_Project_KEL8/assets/130221231/9ae3056b-7483-47be-926b-35d1c010c483)

**Comment by BIMA-25** [comment]
flochat alat udah kelar guys

**Comment by Agnan441** [comment]
![WhatsApp Image 2023-05-29 at 20 51 10](https://github.com/BIMA-25/Final_Project_KEL8/assets/125073437/d3d71ed9-bc44-4562-bc10-9de9bac795e5)
