### ISSUE TITLE
TA-PROGRES 3 Pesan Notifikasi Telegram

### ISSUE THREAD

**Issue by BIMA-25** [BIMA-25/Final_Project_KEL8#16]
BIKIN PESAN YANG BAKALAN KITA KIRIM KE TELEGRAM

**Comment by Mar4iaulfa19** [comment]
Jika gas CO sudah lebih dari 80 ppm , notifikasi pesan yang muncul pada telegram yaitu :
**“PERINGATAN! GAS CO SUDAH DI AMBANG BATAS BAHAYA!”**

Jika gas CO2 sudah lebih dari 1000 ppm, notifikasi peesan yang muncul pada telegram yaitu :
**“PERINGATAN! GAS CO2 SUDAH DI AMBANG BATAS BAHAYA!”** 

Jika gas tolueno sudah lebih dari 100 ppm, notifikasi pesan yang muncul pada telegram yaitu : 
**“PERINGATAN! GAS TOLUENO SUDAH DI AMBANG BATAS BAHAYA!”**

Jika gas NH4 sudah lebih dari 60 ppm, notifikasi pesan yang muncul pada telegram yaitu : 
**“PERINGATAN! GAS NH4 SUDAH DI AMBANG BATAS BAHAYA!”**

Jika gas aceton sudah lebih dari 500 ppm, notifikasi pesan yang muncul pada telegram yaitu : 
**“PERINGATAN! GAS ACETON SUDAH DI AMBANG BATAS BAHAYA!”**
