### ISSUE TITLE
TA-PROGRES 4 BIKIN CODE KONEKSI PEMBACAAN MQ-135

### ISSUE THREAD

**Issue by BIMA-25** [BIMA-25/Final_Project_KEL8#19]
CODE TERSEBUT DAPAT MEMBACA CO, CO2, Toluen, NH4, Aceton

**Comment by Agnan441** [comment]
#include <WiFi.h>
#include <WiFiManager.h>

void setup() {
  // Inisialisasi Serial Monitor
  Serial.begin(115200);

  // Inisialisasi WiFiManager
  WiFiManager wifiManager;

  // Mencoba untuk terhubung ke WiFi yang sudah dikonfigurasi sebelumnya
  if (!wifiManager.autoConnect()) {
    // Jika tidak berhasil terhubung, maka membuat Access Point baru
    // dan meminta pengguna untuk mengkonfigurasi WiFi
    Serial.println("Gagal terhubung ke WiFi dan memulai mode konfigurasi AP");
    delay(3000);
    ESP.restart();
  }

  // Jika berhasil terhubung ke WiFi
  Serial.println("Terhubung ke WiFi!");
  Serial.print("Alamat IP: ");
  Serial.println(WiFi.localIP());
}

void loop() {
  // Kode program lainnya di sini
}

**Comment by BIMA-25** [comment]
ok done ya
