### ISSUE TITLE
TA-PROGRES1 BATASAN MASALAH dan RUMUSAN MASALAH

### ISSUE THREAD

**Issue by BIMA-25** [BIMA-25/Final_Project_KEL8#2]
tentukan BATASAN MASALAH dan RUMUSAN MASALAH dari project kita

**Comment by Mar4iaulfa19** [comment]
Rumusan masalah: 

1. bagaimana merancang sistem monitoring kualitas udara di ruangan tertutup berbasis iot?

Batasan masalah: 
1. alat ini dapat dimonitoring secara realtime menggunakan platform iot.
3. alat ini mampu mendeteksi gas CO, NO2, Amonia, gas organik volatile (VOCs).
4. alat ini dapat memberikan peringatan dini berupa notifikasi di smartphone dan alarm apabila konsentrasi gas-gas berbahaya lebih dari ambang batas.
5. alat ini mampu menjalankan saklar apabila digunakan untuk mengaktifkan sistem ventilasi.
6. alat ini harus terhubung ke jaringan wifi apabila ingin melihat data pembacaan alat dan mengaktifkan fitur saklar.
