### ISSUE TITLE
TA-PROGRES1 rancangan sistem secara general

### ISSUE THREAD

**Issue by BIMA-25** [BIMA-25/Final_Project_KEL8#4]
buat  rancangan sistem secara general dari project kita

**Comment by Agnan441** [comment]
![image](https://github.com/BIMA-25/Final_Project_KEL8/assets/125073437/47dd8565-3d55-464f-a219-ed7186f95da5)

**Comment by BIMA-25** [comment]
aman agnan

**Comment by BIMA-25** [comment]
kalo udah selesai ubah label ke review ya
