### ISSUE TITLE
TA-PROGRES2 PLATFROM IOT

### ISSUE THREAD

**Issue by BIMA-25** [BIMA-25/Final_Project_KEL8#6]
jelasan kenapa kita pilih blink

**Comment by BIMA-25** [comment]
yang poin nomor 2 itu di hapus aja afifah untuk fitur kirim notif di telegram kita langsung koding di alatnya

**Comment by afifahfau246** [comment]
Siap Bim

**Comment by BIMA-25** [comment]
tambahan yang poin nomor 4 kita tidak hanya mengontrol saja tapi dapat memonitoring juga
