### ISSUE TITLE
TA-PROGRES2 FITUR YANG DIGUNAKAN

### ISSUE THREAD

**Issue by BIMA-25** [BIMA-25/Final_Project_KEL8#7]
jelasin fitur fitur apa yang kita gunakan pada project kita

**Comment by Mar4iaulfa19** [comment]
1. ALARM 
Fitur alarm yang digunakan dalam project ini yaitu Buzzer. Buzzer Elektronika adalah sebuah komponen elektronika yang dapat menghasilkan getaran suara berupa gelombang bunyi.  Pada alat ini fungsi buzzer yaitu memberi sinyal alaram berupa bunyi. Jika kualitas udara mengalami peningkatan ke level berbahaya atau melebihi batas normal  maka buzzer akan berbunyi.  

2. NOTIFIKASI
Fitur notifikasi yang digunakan pada project yaitu software Telegram. Notifikasi via Telegram dapat membantu user untuk memantau dan pemberitahuan dini status kualitas udara diruangan. 

3. DASHBOARD 
fitur dashboard yang digunakan yaitu Blynk. Microcontroller yang digunakan dalam alat ini terhubung dengan sebuah platform blynk yang merupakan platform IoT berbasis komputasi awan untuk melakukan pengolahan terhadap nilai yang didapat dari sensor kemudian membandingkan dengan ambang batas aman. Platform ini dimanfaatkan juga untuk mengirimkan notifikasi melalui media pesan, aplikasi Android yaitu telegram  dan memicu pengaktifan buzzer sebagai notifikasi alarm.

**Comment by Mar4iaulfa19** [comment]
Fitur yang digunakan dalam project kelompok kami yaitu : 
1. ALARM 
Fitur alarm yang digunakan dalam project ini yaitu Buzzer. Buzzer Elektronika adalah sebuah komponen elektronika yang dapat menghasilkan getaran suara berupa gelombang bunyi.  Pada alat ini fungsi buzzer yaitu memberi sinyal alaram berupa bunyi. Jika kualitas udara mengalami peningkatan ke level berbahaya atau melebihi batas normal  maka buzzer akan berbunyi.  
2. NOTIFIKASI
Fitur notifikasi yang digunakan pada project yaitu software Telegram. Notifikasi via Telegram dapat membantu user untuk memantau dan pemberitahuan dini status kualitas udara diruangan. 
3. DASHBOARD 
fitur dashboard yang digunakan yaitu Blynk. Microcontroller yang digunakan dalam alat ini terhubung dengan sebuah platform blynk yang merupakan platform IoT berbasis komputasi awan untuk melakukan pengolahan terhadap nilai yang didapat dari sensor kemudian membandingkan dengan ambang batas aman. Platform ini dimanfaatkan juga untuk mengirimkan notifikasi melalui media pesan, aplikasi Android yaitu telegram  dan memicu pengaktifan buzzer sebagai notifikasi alarm.

**Comment by BIMA-25** [comment]
ALARM 
Fitur alarm yang digunakan dalam project ini yaitu Buzzer. Buzzer Elektronika adalah sebuah komponen elektronika yang dapat menghasilkan getaran suara berupa gelombang bunyi.  Pada alat ini fungsi buzzer yaitu memberi sinyal alaram berupa bunyi. Jika kualitas udara mengalami peningkatan ke level berbahaya atau melebihi batas normal  maka buzzer akan berbunyi.  
NOTIFIKASI
Fitur notifikasi yang digunakan pada project yaitu software Telegram. Notifikasi via Telegram dapat membantu user untuk memantau dan pemberitahuan dini status kualitas udara diruangan. 
DASHBOARD 
fitur dashboard yang digunakan yaitu Blynk. fungsi blynk pada alat ini yaitu untuk menampilkan hasil pembacaan sensor yang dibaca oleh alat. 
 // hasil refisi dari ppt
