### ISSUE TITLE
TA-PROGRES2 MIKROKONTROLER YANG DIPILIH

### ISSUE THREAD

**Issue by BIMA-25** [BIMA-25/Final_Project_KEL8#9]
TENTUIN KENAPA KITA PAKE ESP32

**Comment by Agnan441** [comment]
Berikut alasan penggunaan mikrokontroler ESP32 pada project akhir ini:

Pengertian ESp32:
ESP32 adalah mikrokontroler yang dikembangkan oleh Espressif Systems. Memungkinkannya terhubung ke jaringan Wi-Fi dan berkomunikasi dengan perangkat lain melalui Bluetooth. Ditenagai oleh prosesor dual-core dengan kecepatan clock yang tinggi dan dilengkapi dengan RAM yang cukup besar, dengan kinerja yang baik untuk mengeksekusi kode dan menangani tugas yang kompleks.

Kelebihan ESP32:
1.	Kemampuan Wi-Fi dan Bluetooth terintegrasi.
2.	Kinerja yang baik dengan prosesor dual-core dan RAM yang cukup besar.
3.	Konsumsi daya yang rendah.
4.	Dukungan untuk berbagai antarmuka seperti SPI, I2C, UART, dan GPIO
5.	Harga yang terjangkau.

Kekurangan ESP32:
1.	Dokumentasi resmi dan dukungan pengembang dapat kurang memadai.
2.	Konsumsi daya yang tinggi saat menggunakan fitur nirkabel.
3.     Kompatibilitas perangkat lunak yang mungkin memerlukan penyesuaian
